[package]
name = "RustDockerHelloWorld"
version = "0.1.0"
authors = ["Matthew Casperson <matthewcasperson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
